### ISSUE TITLE
ModuleNotFoundError: No module named 'config.settings'

### ISSUE THREAD

**Issue by Eric-sson** [Nezreka/SoulSync#17]
I am receiving the below error once I start the docker container on my Unraid server.

Traceback (most recent call last):
  File "/app/web_server.py", line 22, in <module>
    from config.settings import config_manager
ModuleNotFoundError: No module named 'config.settings'

Is there anything that I am missing in my configuration?

This is the docker compose that I am using:

services:
  SoulSync:

    command:
      - "python"
      - "web_server.py"

    container_name: "SoulSync"

    environment:
      - "TZ=Europe/Brussels"
      - "HOST_OS=Unraid"
      - "PUID=99"
      - "PGID=100"
      - "UMASK=002"
      - "PYTHONPATH=/app"
      - "HOST_HOSTNAME=Tower"
      - "HOST_CONTAINERNAME=SoulSync"
      - "FLASK_ENV=production"
      - "PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "LANG=C.UTF-8"
      - "GPG_KEY=A035C8C19219BA821ECEA86B64E628F8D684696D"
      - "PYTHON_VERSION=3.11.13"
      - "PYTHON_SHA256=8fb5f9fbc7609fa822cb31549884575db7fd9657cbffb89510b5d7975963a83a"
      - "FLASK_APP=web_server.py"

    hostname: "06fe5a46f796"

    image: "boulderbadgedad/soulsync:latest"

    ipc: "private"

    labels:
      net.unraid.docker.icon: "https://github.com/Nezreka/SoulSync/blob/main/assets/trans.png"
      net.unraid.docker.managed: "dockerman"
      net.unraid.docker.webui: "http://[IP]:[PORT:8008]/"

    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "50m"

    network_mode: "bridge"

    ports:
      - "8008:8008/tcp"
      - "8888:8888/tcp"
      - "8889:8889/tcp"

    user: "soulsync"

    volumes:
      - "/mnt/cache/appdata/soulsync/database:/app/database"
      - "/mnt/cache/appdata/soulsync/logs:/app/logs"
      - "/mnt/cache/appdata/soulsync:/app/config"
      - "/mnt/remotes/SYNOLOGY_data/downloads/music/slskd/complete:/app/downloads"
      - "/mnt/remotes/SYNOLOGY_data/downloads/music/slskd/transfer:/app/Transfer"
      - "/mnt/remotes/SYNOLOGY_data/media/music:/music:ro"

    working_dir: "/app"

version: "3.6"

Is there anything that I am missing in my configuration?

**Comment by joelis10** [comment]
I get this too and assume it's because I'm missing the config file, but I can't see where it's supposed to go?

**Comment by connorpink** [comment]
Happening for me as well. getting the same error. also using docker. deployed for the first time yesterday.

**Comment by Nezreka** [comment]
Unfortunately I don't have an unraid setup to test any fixes or solutions :( I did add an unraid.md with setup instructions but I can't verify it works, just that it should work lol. The file is in the repo.

**Comment by Nezreka** [comment]
try this: 

  Volume mapping is incorrect:
  - "/mnt/cache/appdata/soulsync:/app/config"  # ❌ WRONG

  Should be:
  - "/mnt/cache/appdata/soulsync/config:/app/config"  # ✅ CORRECT

**Comment by Eric-sson** [comment]
> try this:
> 
> Volume mapping is incorrect:
> 
> * "/mnt/cache/appdata/soulsync:/app/config"  # ❌ WRONG
> 
> Should be:
> 
> * "/mnt/cache/appdata/soulsync/config:/app/config"  # ✅ CORRECT

I tried that. But for me still the same error.
I also created the config.json manually in that folder but no luck.

Traceback (most recent call last):
  File "/app/web_server.py", line 22, in <module>
    from config.settings import config_manager
ModuleNotFoundError: No module named 'config.settings'

**Comment by Nezreka** [comment]
Hmm try this:   

Change this line in your docker-compose:

  From:
  - "/mnt/cache/appdata/soulsync:/app/config"

  To:
  - "/mnt/cache/appdata/soulsync/config.json:/app/config/config.json"

I also updated the template and unraid.md helper files

**Comment by Eric-sson** [comment]
> Hmm try this:
> 
> Change this line in your docker-compose:
> 
> From:
> 
> * "/mnt/cache/appdata/soulsync:/app/config"
> 
> To:
> 
> * "/mnt/cache/appdata/soulsync/config.json:/app/config/config.json"
> 
> I also updated the template and unraid.md helper files

I do receive another error now:

Traceback (most recent call last):
  File "/app/web_server.py", line 29, in <module>
    from core.database_update_worker import DatabaseUpdateWorker, DatabaseStatsWorker
  File "/app/core/database_update_worker.py", line 39, in <module>
    from database import get_database, MusicDatabase
ImportError: cannot import name 'get_database' from 'database' (unknown location)

**Comment by Nezreka** [comment]
oh nice progress! try this:

  Change this:

  From:
  - "/mnt/cache/appdata/soulsync/database:/app/database"

  To:
  - "/mnt/cache/appdata/soulsync/database:/app/data"

  Then you need to update your config.json to point to the new path:
  {
    "database": {
      "path": "data/music_library.db",
      "max_workers": 5
    }
  }

**Comment by Eric-sson** [comment]
> * /app/data

This seems to work! UI is loading now for me :)

**Comment by Nezreka** [comment]
Fantastic, i'll keep this ticket open for any others that experience the same thing. Thanks for your help solving it.

**Comment by joelis10** [comment]
Changing the internal path to `/app/config/config.json` and creating the file manually worked for me

**Comment by richard-lee-863** [comment]
I could only seem to get this working if allowing to run as root.. Which I never want to do. Tried setting UID and GUID to the Unraid defaults 99:100 and creating folders / config.json under that user. But it wasn't happy.

**Comment by Eric-sson** [comment]
> Fantastic, i'll keep this ticket open for any others that experience the same thing. Thanks for your help solving it.

I do see this error when the container starts: WARNING: config.json not found at /config/config.json. Using default settings.

Also when I change the settings in the UI and click Save Settings I get: Failed to save settings: [Errno 13] Permission denied: 'config/config.json'

Is this some permission issue? I do have PUID 99 and PGID 100 set which are the Unraid defaults.

**Comment by Nezreka** [comment]
I just fixed this issue. Will need to pull the newest image from docker hub. config file should now always appear in config folder.

**Comment by framedr0p** [comment]
I can confirm, that it works now!! The Web UI is loading. I will configure it now for me and keep testing.
Thanks für the Update!

Unraid 7.1.4

**Comment by richard-lee-863** [comment]
Yea same here, working with latest image thankfully.

**Comment by PedanXr** [comment]
Using the latest image from "boulderbadgedad/soulsync:latest" I still get this error:

```
Traceback (most recent call last):
File "/app/web_server.py", line 22, in 
from config.settings import config_manager
ModuleNotFoundError: No module named 'config.settings'
```

Tested it with the path for /app/config commented out and not. Both do not work.

**Comment by joelis10** [comment]
try using `/path/to/config.json:/app/config/config.json` as the path and create a `config.json` file in the host path, with nothing in it other than `{}`

**Comment by Nezreka** [comment]
chmod issue should also now be resolved in newest image

**Comment by PedanXr** [comment]
Hi, I tried the before mentioned solutions (mounting the config directly with only the starting brackets in it, mounting the config directly with the contents of the example config and also mounting only the /app/config directory with the new image) but I still get the same error

**Comment by framedr0p** [comment]
> Hi, I tried the before mentioned solutions (mounting the config directly with only the starting brackets in it, mounting the config directly with the contents of the example config and also mounting only the /app/config directory with the new image) but I still get the same error

In an UNRAID machine?
if u look at the file with ls -al who is owner and group and how are the permissions?

**Comment by PedanXr** [comment]
I am running this on a debian docker host without unraid. Managed via komodo. Container is run as 1000:100 (pedan:users).

```
pedan@dockarr:/etc/komodo/stacks/arr-stack/soulsync$ ls -al
total 16
drwxr-xr-x  4 pedan users 4096 Sep 16 08:19 .
drwxr-xr-x 28 pedan users  4096 Sep 15 17:21 ..
drwxr-xr-x  2 pedan users 4096 Sep 16 08:34 config
drwxr-xr-x  2 pedan users 4096 Sep 15 17:21 logs
```

**Comment by mavproductions** [comment]
Getting issues on TrueNAS
```yaml
networks:
  default:
    name: soulsync-network
services:
  soulsync:
    container_name: soulsync
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
      - FLASK_ENV=production
      - PYTHONPATH=/app
      - SOULSYNC_CONFIG_PATH=/app/config/config.json
      - TZ=America/New_York
    extra_hosts:
      - host.docker.internal:host-gateway
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 60s
      test:
        - CMD
        - curl
        - '-f'
        - http://localhost:8888/
      timeout: 10s
    image: boulderbadgedad/soulsync:latest
    ports:
      - '8008:8008'
      - '8888:8888'
      - '8889:8889'
    restart: unless-stopped
    volumes:
      #- /mnt/MAIN/TrueNAS/truenas-apps/soulsync/config:/app/config
      #- /mnt/MAIN/TrueNAS/truenas-apps/soulsync/data:/app/data
      #- /mnt/MAIN/TrueNAS/truenas-apps/soulsync/logs:/app/logs
      #- /mnt/MAIN/TrueNAS/truenas-apps/soulsync/downloads:/app/downloads
      - /mnt/MAIN/_smb_mounts/itunes:/music:ro
volumes:
  soulsync_database:
    driver: local
```

Having a lot of issues with persistent volumes on my setup. With the commented volumes, it works, but I'd like to have them uncommented where possible. I even tried PUID/PGID both set to 0 and the app was still getting permissions denied errors on the log mount. :s

I might try frigging around with non-persistent volumes for now, until I figure out what seems to be like a simple issue on my end with TrueNAS.

**Comment by runawaydevil** [comment]
Someone found how to do? I tried all above and nothing, same error.

**Comment by weasalNZ** [comment]
trying to run with the current template on unraid and this is the below error:
I have tried to manually create the config.json under /appdata/soulsync/config.json 

docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/mnt/user/appdata/soulsync/config.json" to rootfs at "/app/config/config.json": mount /mnt/user/appdata/soulsync/config.json:/app/config/config.json (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.

**Comment by psycotica0** [comment]
Hey folks! Just ran into this, and the issue here is that the code in the docker image is in `/app`, so when the code tries to load the "config.settings" module, that means `/app/config/settings.py`, but if we follow the instructions to mount our host's config folder onto `/app/config/` it overwrites the whole directory, meaning there _isn't_ a `/app/config/settings.py` anymore.

This is why the change was suggested to only bind the `/app/config/config.json` and not the whole folder. But I assume this could also be solved by just mounting to `/config` and using `SOULSYNC_CONFIG_PATH=/config/config.json` to dodge the entire issue. The same thing is true of the `/app/logs` and `/app/database` folders, I assume.

**Comment by psycotica0** [comment]
Hmm, I'm actually a little dubious about `SOULSYNC_CONFIG_PATH`... I can't find where the code reads it?

**Comment by georgemaxim** [comment]
I have same issue on synology dsm 7.2.x

```
<head></head>
ImportError: cannot import name 'get_database' from 'database' (unknown location)
--
from database import get_database, MusicDatabase
File "/app/core/database_update_worker.py", line 39, in <module>
from core.database_update_worker import DatabaseUpdateWorker, DatabaseStatsWorker
File "/app/web_server.py", line 35, in <module>
Traceback (most recent call last):
🚀 Starting SoulSync Web Server...
 
UMASK: 0022
User: 1026:100 (soulsync:users)
👤 Running as:
🎭 Setting UMASK to 022
✅ User/Group IDs already correct
UMASK: 022
PGID: 100
PUID: 1026
📝 User Configuration:
🐳 SoulSync Container Starting...


```

**Comment by liyang1105** [comment]
I encountered the exact same issue when deploying via Portainer on Synology 7.2.2. I eventually resolved it by making the changes mentioned above.

After these changes everything worked fine for me.

From:
"/mnt/cache/appdata/soulsync:/app/config"
To:
"/mnt/cache/appdata/soulsync/config.json:/app/config/config.json"

From:
"/mnt/cache/appdata/soulsync/database:/app/database"
To:
"/mnt/cache/appdata/soulsync/database:/app/data"

**Comment by lukyjay** [comment]
> I encountered the exact same issue when deploying via Portainer on Synology 7.2.2. I eventually resolved it by making the changes mentioned above.
> 
> After these changes everything worked fine for me.
> 
> From: "/mnt/cache/appdata/soulsync:/app/config" To: "/mnt/cache/appdata/soulsync/config.json:/app/config/config.json"
> 
> From: "/mnt/cache/appdata/soulsync/database:/app/database" To: "/mnt/cache/appdata/soulsync/database:/app/data"

I have done this and I still experience this issue. Changing the mount to the config.json file replaces the error with a database not found error:
ImportError: cannot import name 'get_database' from 'database' (unknown location)

Then changing the config file and the database mount directory does nothing.

I also changed the container so it runs as root and that does not seem to work either.

**Comment by Nezreka** [comment]
Sorry for these docker issues, it's a bit new to me but its now my top priority to fix these problems. I just pushed a new image to the repo that hopefully solves the config file issue.

**Comment by lukyjay** [comment]
> Sorry for these docker issues, it's a bit new to me but its now my top priority to fix these problems. I just pushed a new image to the repo that hopefully solves the config file issue.

I fixed it by manually downloading the needed files from GitHub

**Comment by Nezreka** [comment]
This issue should now be resolved with the latest update to repo and image. Database info is now moved to the db bypassing the config file
