### ISSUE TITLE
Wishlist wont scan

### ISSUE THREAD

**Issue by blastronaut** [Nezreka/SoulSync#44]
"Error starting scan: Wishlist auto-processing is currently running. Please wait for it to complete before starting a watchlist scan."

It says my wishlist is auto-processing.. It is not scanning its stuck thinking that it's scanning. 

Last scanned date was 3 days ago.

nothing in the logs..

-8190-b61b42df72c5
xx.xx.xx.xx - - [07/Oct/2025 00:57:33] "GET /api/activity/feed HTTP/1.1" 200 -
xx.xx.xx.xx - - [07/Oct/2025 00:57:33] "GET /api/activity/toasts HTTP/1.1" 200 -
xx.xx.xx.xx - - [07/Oct/2025 00:57:33] "GET /api/download_status/batch?batch_ids=d2c92516-0152-4360-8551-46c1e2052e74 HTTP/1.1" 200 -
xx.xx.xx.xx - - [07/Oct/2025 00:57:33] "GET /api/downloads/status HTTP/1.1" 200 -
xx.xx.xx.xx - - [07/Oct/2025 00:57:33] "GET /api/system/stats HTTP/1.1" 200 -
xx.xx.xx.xx - - [07/Oct/2025 00:57:33] "GET /api/wishlist/count HTTP/1.1" 200 -
xx.xx.xx.xx - - [07/Oct/2025 00:57:33] "GET /api/activity/feed HTTP/1.1" 200 -
xx.xx.xx.xx - - [07/Oct/2025 00:57:33] "GET /api/activity/toasts HTTP/1.1" 200 -
xx.xx.xx.xx - - [07/Oct/2025 00:57:33] "GET /api/system/stats HTTP/1.1" 200 -
xx.xx.xx.xx - - [07/Oct/2025 00:57:33] "GET /api/activity/toasts HTTP/1.1" 200 -
xx.xx.xx.xx - - [07/Oct/2025 00:57:33] "GET /api/activity/feed HTTP/1.1" 200 -
xx.xx.xx.xx - - [07/Oct/2025 00:57:33] "GET /api/database/stats HTTP/1.1" 200 -
xx.xx.xx.xx - - [07/Oct/2025 00:57:33] "GET /status HTTP/1.1" 200 -
xx.xx.xx.xx - - [07/Oct/2025 00:57:33] "GET /status HTTP/1.1" 200 -
xx.xx.xx.xx - - [07/Oct/2025 00:57:33] "GET /api/download_status/batch?batch_ids=d2c92516-0152-4360-8551-46c1e2052e74 HTTP/1.1" 200 -
xx.xx.xx.xx - - [07/Oct/2025 00:57:34] "GET /api/downloads/status HTTP/1.1" 200 -
xx.xx.xx.xx - - [07/Oct/2025 00:57:34] "GET /status HTTP/1.1" 200 -

<img width="777" height="679" alt="Image" src="https://github.com/user-attachments/assets/d4a2a371-9752-4a58-b088-02665f293ae2" />

**Comment by Nezreka** [comment]
oh ill get this sorted out! I must have borked in a recent update

**Comment by Nezreka** [comment]
The newest docker image and repo include the update that will fix this issue.

**Comment by Nezreka** [comment]
But to be clear, the watchlist will not scan if the wishlist is in the middle of processing. It will wait 10 min in a loop until the wishlist finishes and then it will begin the scan. Will scan once every 24 hrs

**Comment by blastronaut** [comment]
I just pulled the newest repo, and restarted my docker instance.. and its
still saying the same error... the logs have nothing about scanning or
wishlist mentioned.

last scan was still 4 days ago :(

**Comment by Nezreka** [comment]
That is quite odd, and for sure you have updated to the newest code and restarted the app? What should be happening is, 1 minute after starting the app the auto wishlist processing begins and if any items are in there it will process them. 10 minutes after launch the watchlist will begin scanning for new releases, if the wishlist is scanning, it will pause for 10 minutes. Once it is able to run, it will wait 24 hours before attempting again. Is is possible you are trying to run the watchlist while the wishlist is scanning?

**Comment by blastronaut** [comment]
yes i am on docker latest

***@***.***:/x/x/soulsync# docker inspect soulsync-webui --format
'{{.Config.Image}}'
boulderbadgedad/soulsync:latest

re-created docker image with latest pull..

watchlist can't scan because wishlist is "scanning"

[image: image.png]

wishlist - is NOT scanning

[image: image.png]

I can also confirm it's reset because it made me re-auth my spotify.

**Comment by Nezreka** [comment]
Curious, if you go to the artists page. can you search an artist, select it and view their discog?

This still  seems to point to old code which is odd. I pushed the new image little over an hour ago so I would expect it to be live.

**Comment by blastronaut** [comment]
I can search artists no problem. This works great

The Library feature however never loads - “failed to load artists”

**Comment by Nezreka** [comment]
Dos Problemas! Okay well that shouldn't happen. Are you using plex, jellyfin or navidrome?

**Comment by Nezreka** [comment]
Can you try this: 

  docker pull boulderbadgedad/soulsync:latest --no-cache
  docker stop soulsync-webui
  docker rm soulsync-webui
  docker run ... # recreate container

**Comment by blastronaut** [comment]
I think I may have found the bug...

I think my slskd got disconnected WHILE a scan was happening. So the status
of my slskd showed it was still connected (and scanning?) in soulsync even
thought it was not.

I reconnected slskd now its adding the watchlist.

I am still unable to use the Library, and noticed my log has a bunch of
calls for a new music beatport list? i dont see anywhere in the interface..
sorry for hijacking this ticket. LOL

2025-10-07 14:52:22 - newmusic - [92mINFO [0m -
get_beatport_featured_charts:2491 - âœ… Chart 88: Flowers & Guns by 8Kays
2025-10-07 14:52:22 - newmusic - [92mINFO [0m -
get_beatport_featured_charts:2491 - âœ… Chart 89: Roma suona by Lady Maru
2025-10-07 14:52:22 - newmusic - [92mINFO [0m -
get_beatport_featured_charts:2491 - âœ… Chart 90: Sektor 0 by Nous Klear
2025-10-07 14:52:22 - newmusic - [92mINFO [0m -
get_beatport_featured_charts:2491 - âœ… Chart 91: Golden Age of Liquid by
Danny Byrd
2025-10-07 14:52:22 - newmusic - [92mINFO [0m -
get_beatport_featured_charts:2491 - âœ… Chart 92: Come Together VIP by
Urbandawn
2025-10-07 14:52:22 - newmusic - [92mINFO [0m -
get_beatport_featured_charts:2491 - âœ… Chart 93: Maraâ€™s Dancefloor
Detonators by Mara (CH)
2025-10-07 14:52:22 - newmusic - [92mINFO [0m -
get_beatport_featured_charts:2491 - âœ… Chart 94: Dubstep Selection by
Tik&Borrow (Sep 2025) by Tik&Borrow
2025-10-07 14:52:22 - newmusic - [92mINFO [0m -
get_beatport_featured_charts:2491 - âœ… Chart 95: Slow Ascension by Ayesha
2025-10-07 14:52:22 - newmusic - [92mINFO [0m -
get_beatport_featured_charts:2491 - âœ… Chart 96: Nightrider Chart by Karla
Blum
2025-10-07 14:52:22 - newmusic - [92mINFO [0m -
get_beatport_featured_charts:2491 - âœ… Chart 97: PRO ENERGIA by LUCATI

**Comment by Nezreka** [comment]
No worries I'm glad we sorted out the wishlist problem. The library page failing is an issue though. The beatport are likely from the scrape that happens once every hour of the homepage. There is a beatport tab on the sync page where you can find music charts for nearly every genre. Is there any info in the browser console when the library page fails?

**Comment by blastronaut** [comment]
the artist sync issue is giving an error in console..

script.js:18563  GET
http://x.x.x.x:x/api/library/artists?search=&letter=all&page=1&limit=75
500 (INTERNAL SERVER ERROR)
loadLibraryArtists @ script.js:18563
initializeLibraryPage @ script.js:18467
loadPageData @ script.js:432
navigateToPage @ script.js:385
(anonymous) @ script.js:343
script.js:18586 ❌ Error loading library artists: Error: 'MusicDatabase'
object has no attribute 'get_library_artists'
    at loadLibraryArtists (script.js:18567:19)


This is the GET result...
{"artists":[],"error":"'MusicDatabase' object has no attribute
'get_library_artists'","pagination":{"has_next":false,"has_prev":false,"limit":75,"page":1,"total_count":0,"total_pages":0},"success":false}

I'm using navidrome, it's connected fine and passing artists into the
naivdrome correctly..

I've also tested on a couple different devices and it's the same across
these..


My docker compose

services:
  soulsync:
    image: boulderbadgedad/soulsync:latest
    container_name: soulsync-webui
    environment:
      # User/Group ID configuration
      - PUID=x
      - PGID=x
      - UMASK=x
      # Web server configuration
      - FLASK_ENV=production
      - PYTHONPATH=/app
      # Optional: Configure through environment variables
      - SOULSYNC_CONFIG_PATH=/app/config/config.json
      # Set timezone
      - TZ=XXX/XXX
    ports:
      - "8008:8008"      # Main web app
      - "8888:8888"      # Spotify OAuth callback
      - "8889:8889"      # Tidal OAuth callback
    volumes:
      # Persistent data volumes
      # - ./config:/app/config
      - ./config/config.json:/app/config/config.json # <-- NEW/FIXED LINE
      - ./logs:/app/logs
      - /XXX/XXX/Downloads:/app/downloads
      # Use named volume for database persistence (separate from host
database)
      - soulsync_database:/app/database
      - /XXX/XXX:/XXX/XXX:rw
      # IMPORTANT: Mount the drives containing your download and transfer
folders
      # If your download/transfer paths are on E: drive, mount E: drive:
      # - /mnt/e:/host/mnt/e:rw
      # Mount H: drive for transfer folder
      # - /mnt/h:/host/mnt/h:rw
      # If your download/transfer paths are on C: drive, uncomment this
line:
      # - /mnt/c:/host/mnt/c:rw
      # If your download/transfer paths are on D: drive, uncomment this
line:
      # - /mnt/d:/host/mnt/d:rw
      # Add additional drive mounts as needed for your specific setup
      # Optional: Mount your music library for Plex/Jellyfin access
      - /XXX/XXX/Music:/music:ro
    extra_hosts:
      # Allow container to reach host services
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    # Resource limits (adjust as needed)
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M
# Named volumes for persistent data
volumes:
  soulsync_database:
    driver: local
# Optional: Add external network for communication with other containers
networks:
  default:
    name: soulsync-network



maybe the only thing odd about my config is i also added jellyfin? does it
not allow 2x connections at once maybe?

  "active_media_server": "navidrome", is set...

**Comment by Nezreka** [comment]
okay one more check. can you run this:


  docker-compose down
  docker pull boulderbadgedad/soulsync:latest --no-cache
  docker-compose up -d


I just pushed the image again on the chance the other image had issues. I'm sorry about this headache. I'm quite new to docker in general

**Comment by blastronaut** [comment]
nah same error..

# docker-compose down
WARNING: The following deploy sub-keys are not supported and have been
ignored: resources.reservations.cpus
Stopping soulsync-webui ... done
Removing soulsync-webui ... done
Removing network soulsync-network
c# docker pull boulderbadgedad/soulsync:latest
latest: Pulling from boulderbadgedad/soulsync
8c7716127147: Already exists
44350d10c02e: Already exists
4dc2c3222cdb: Already exists
b25238518c0c: Already exists
fdd6f3819436: Already exists
35082c89c5e0: Pull complete
f8c957adffcf: Pull complete
ac744900953a: Pull complete
75d17ee5c717: Pull complete
cd6806b36c38: Pull complete
e74753601912: Pull complete
070c1e8f3e86: Pull complete
e60c86ff5f65: Pull complete
e142a736abca: Pull complete
Digest:
sha256:955fd5975e7bc4241a47e0eb760b84a67573818eabc628499cfd01ca648e375e
Status: Downloaded newer image for boulderbadgedad/soulsync:latest
docker.io/boulderbadgedad/soulsync:latest
# docker-compose up -d
WARNING: The following deploy sub-keys are not supported and have been
ignored: resources.reservations.cpus
Creating network "soulsync-network" with the default driver
Creating soulsync-webui ... done
#


script.js:18563 GET
http://MYIPINFO/api/library/artists?search=&letter=all&page=1&limit=75
<http://10.88.88.88:8008/api/library/artists?search=&letter=all&page=1&limit=75>
500 (INTERNAL SERVER ERROR)
loadLibraryArtists @ script.js:18563
initializeLibraryPage @ script.js:18467
loadPageData @ script.js:432
navigateToPage @ script.js:385
(anonymous) @ script.js:343
script.js:18586 ❌ Error loading library artists: Error: 'MusicDatabase'
object has no attribute 'get_library_artists' at loadLibraryArtists (
script.js:18567:19)

**Comment by Nezreka** [comment]
oh crap! hold on it may be my fault

**Comment by Nezreka** [comment]
Try this: 

  docker-compose down
  docker image rm boulderbadgedad/soulsync:latest
  docker-compose pull
  docker-compose up -d

**Comment by blastronaut** [comment]
same error :(

script.js:18454 🔧 Initializing Library page...
script.js:18470 ✅ Library page initialized successfully
script.js:18563  GET
http://xxxxxx/api/library/artists?search=&letter=all&page=1&limit=75 500
(INTERNAL SERVER ERROR)
loadLibraryArtists @ script.js:18563
initializeLibraryPage @ script.js:18467
loadPageData @ script.js:432
navigateToPage @ script.js:385
(anonymous) @ script.js:343
script.js:18586 ❌ Error loading library artists: Error: 'MusicDatabase'
object has no attribute 'get_library_artists'
    at loadLibraryArtists (script.js:18567:19)
overrideMethod @ hook.js:608
loadLibraryArtists @ script.js:18586
await in loadLibraryArtists
initializeLibraryPage @ script.js:18467
loadPageData @ script.js:432
navigateToPage @ script.js:385
(anonymous) @ script.js:343

**Comment by Nezreka** [comment]
For sure your URL, username and password are all correct for navidrome in settings?

**Comment by blastronaut** [comment]
yes, navidrome is working correctly.. if I put the wrong user/password in I
get an error

otherwise i am getting this..
navidrome connection successful
Connection Test: Navidrome connection successful

**Comment by blastronaut** [comment]
similar error if i change my connection to jellyfin server (which is also
correctly connected)

Failed to load resource: the server responded with a status of 500
(INTERNAL SERVER ERROR)
hook.js:608 ❌ Error loading library artists: Error: 'MusicDatabase' object
has no attribute 'get_library_artists' at loadLibraryArtists (
script.js:18567:19)
overrideMethod @ hook.js:608
:8008/api/library/ar…m&page=1&limit=75:1 Failed to load resource: the
server responded with a status of 500 (INTERNAL SERVER ERROR)
hook.js:608 ❌ Error loading library artists: Error: 'MusicDatabase' object
has no attribute 'get_library_artists' at loadLibraryArtists (
script.js:18567:19)

**Comment by Nezreka** [comment]
Do you still have the same soulsync db populated from navidrome? if so, can you run a full refresh on it?

**Comment by blastronaut** [comment]
just did a full scan still getting the API error internal 500

Navidrome Database Updater Last Full Refresh: 10/7/2025, 7:06:05 PM

**Comment by Nezreka** [comment]
Okay Im wondering if it was old .pyc files that were being used in the build process. can you please try pulling the newest code once more? I'm sorry for this whole deal.

**Comment by blastronaut** [comment]
No worries, happy to help you debug..

Still the same library api error...

all the other api calls seem to be returning 200s

Failed to load resource: the server responded with a status of 500
(INTERNAL SERVER ERROR)
❌ Error loading library artists: Error: 'MusicDatabase' object has no
attribute 'get_library_artists' at loadLibraryArtists (script.js:18567:19) at
async loadPageData (script.js:435:25)
overrideMethod @ chrome-extension://f…ld/installHook.js:1

If i directly load the URL in browser I get this..

{"artists":[],"error":"'MusicDatabase' object has no attribute
'get_library_artists'","pagination":{"has_next":false,"has_prev":false,"limit":75,"page":1,"total_count":0,"total_pages":0},"success":false}



Navidrome Database Updater

Last Full Refresh: 10/7/2025, 7:06:05 PM
Artists:3,831
Albums:6,469
Tracks:63,162
Size:22.71 MB

**Comment by Nezreka** [comment]
Okay lets try this again XD

  docker-compose down
  docker volume rm soulsync_database
  docker rmi boulderbadgedad/soulsync:latest
  docker pull boulderbadgedad/soulsync:latest
  docker-compose up -d

need to make sure we entirely remove everything from the old image and container and volume just to be sure.

**Comment by blastronaut** [comment]
yup, that fixed it.

for some reason my soulsync db was called this..

"soulsync_soulsync_database"

had to run this:

docker volume rm soulsync_soulsync_database

i obviously had to rebuild my database, and it worked fine afterward.

nice work!

**Comment by Nezreka** [comment]
yay!! So sorry about that.
